## Q-6. ##
A pharmaceutical company is developing a drug that is supposed to reduce blood
pressure. They conduct a clinical trial with 100 patients and record their blood
pressure before and after taking the drug. The company wants to know if the change
in blood pressure follows a normal distribution.

https://drive.google.com/file/d/1mCjtYHiX--mMUjicuaP2gH3k-SnFxt8Y/view?usp=share_

In [8]:
import pandas as pd

In [9]:
data = pd.read_csv("data.csv")
data

    Patient ID   Blood Pressure Before (mmHg)   Blood Pressure After (mmHg)
0            1                            130                           120
1            2                            142                           135
2            3                            120                           118
3            4                            135                           127
4            5                            148                           140
..         ...                            ...                           ...
95          96                            136                           129
96          97                            143                           137
97          98                            127                           123
98          99                            139                           135
99         100                            135                           130

[100 rows x 3 columns]

In [10]:
data["Blood Pressure Difference (in mmHg)"] = data[" Blood Pressure Before (mmHg)"] - data[" Blood Pressure After (mmHg)"]
data

,Patient ID,Blood Pressure Before (mmHg),Blood Pressure After (mmHg),Blood Pressure Difference (in mmHg)
0,1,130,120,10
1,2,142,135,7
2,3,120,118,2
3,4,135,127,8
4,5,148,140,8
...,...,...,...,...
95,96,136,129,7
96,97,143,137,6
97,98,127,123,4
98,99,139,135,4
99,100,135,130,5

In [11]:
from scipy.stats import shapiro

In [12]:
# Perform the Shapiro-Wilk test
statistic, p_value = shapiro(data["Blood Pressure Difference (in mmHg)"])
alpha = 0.05  # Set the significance level

# Check the null hypothesis
if p_value > alpha:
    print("The data follows a normal distribution.")
else:
    print("The data does not follow a normal distribution.")

The data does not follow a normal distribution.